[[constraint]]
  name = "github.com/labstack/echo"
  version = "2.0.2"

[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = "1.10.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/topfreegames/extensions"
  version = "5.9.0"

[[constraint]]
  name = "github.com/mailru/easyjson"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
