healthcheck:
  workingText: WORKING

redis:
  host: localhost
  port: 1234
  connectionTimeout: 200

api:
  maxReturnedMembers: 2000

jaeger:
  disabled: false
  samplingProbability: 1.0

newrelic:
  key: ""

worker:
  expirationCheckInterval: 1s
  expirationLimitPerRun: 100

extensions:
  dogstatsd:
    host: localhost:8125
    prefix: podium.
    tags_prefix: ""
    rate: 1
